CREATE TABLE customer (
  customer_id  NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cif_no       VARCHAR2(20)  NOT NULL UNIQUE,
  full_name    VARCHAR2(200) NOT NULL,
  id_number    VARCHAR2(20)  NOT NULL UNIQUE,
  phone        VARCHAR2(20),
  status       VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL
               CHECK (status IN ('ACTIVE', 'CLOSED')),
  created_at   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  version      NUMBER(10)    DEFAULT 0 NOT NULL
);

CREATE TABLE account (
  account_id   NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_no   VARCHAR2(20)  NOT NULL UNIQUE,
  customer_id  NUMBER(19)    NOT NULL REFERENCES customer (customer_id),
  account_type VARCHAR2(10)  NOT NULL CHECK (account_type IN ('CURRENT', 'SAVING')),
  currency     CHAR(3)       DEFAULT 'VND' NOT NULL,
  balance      NUMBER(19,2)  DEFAULT 0 NOT NULL,
  hold_amount  NUMBER(19,2)  DEFAULT 0 NOT NULL,
  status       VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL
               CHECK (status IN ('ACTIVE', 'BLOCKED', 'CLOSED')),
  opened_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  version      NUMBER(10)    DEFAULT 0 NOT NULL,
  CONSTRAINT ck_account_balance CHECK (balance >= 0),
  CONSTRAINT ck_account_hold    CHECK (hold_amount >= 0 AND hold_amount <= balance)
);
CREATE INDEX ix_account_customer ON account (customer_id);

CREATE TABLE txn (
  txn_id       NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  txn_ref      VARCHAR2(40)  NOT NULL UNIQUE,
  txn_type     VARCHAR2(20)  NOT NULL
               CHECK (txn_type IN ('DEPOSIT', 'WITHDRAW', 'INTERNAL_TRANSFER', 'INTERBANK_TRANSFER')),
  amount       NUMBER(19,2)  NOT NULL CHECK (amount > 0),
  fee          NUMBER(19,2)  DEFAULT 0 NOT NULL,
  currency     CHAR(3)       DEFAULT 'VND' NOT NULL,
  status       VARCHAR2(10)  NOT NULL
               CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'UNKNOWN')),
  channel      VARCHAR2(10)  NOT NULL CHECK (channel IN ('TELLER', 'DIGITAL', 'PARTNER')),
  description  VARCHAR2(500),
  created_at   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE journal_entry (
  entry_id      NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  txn_id        NUMBER(19)   NOT NULL REFERENCES txn (txn_id),
  account_id    NUMBER(19)   NOT NULL REFERENCES account (account_id),
  dr_cr         CHAR(1)      NOT NULL CHECK (dr_cr IN ('D', 'C')),
  amount        NUMBER(19,2) NOT NULL CHECK (amount > 0),
  balance_after NUMBER(19,2) NOT NULL,
  created_at    TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_je_txn          ON journal_entry (txn_id);
CREATE INDEX ix_je_account_time ON journal_entry (account_id, created_at);